package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 16 14:12:20 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StnLineEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(StnLineEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        StnLineId {
            public Object get(StnLineEOImpl obj) {
                return obj.getStnLineId();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setStnLineId((Number)value);
            }
        }
        ,
        Stn {
            public Object get(StnLineEOImpl obj) {
                return obj.getStn();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setStn((String)value);
            }
        }
        ,
        Color {
            public Object get(StnLineEOImpl obj) {
                return obj.getColor();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        Bpo {
            public Object get(StnLineEOImpl obj) {
                return obj.getBpo();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setBpo((String)value);
            }
        }
        ,
        Part {
            public Object get(StnLineEOImpl obj) {
                return obj.getPart();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setPart((String)value);
            }
        }
        ,
        StnQty {
            public Object get(StnLineEOImpl obj) {
                return obj.getStnQty();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setStnQty((Number)value);
            }
        }
        ,
        ProdLine {
            public Object get(StnLineEOImpl obj) {
                return obj.getProdLine();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setProdLine((Number)value);
            }
        }
        ,
        ChangInvOrg {
            public Object get(StnLineEOImpl obj) {
                return obj.getChangInvOrg();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setChangInvOrg((String)value);
            }
        }
        ,
        TimeCal {
            public Object get(StnLineEOImpl obj) {
                return obj.getTimeCal();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setTimeCal((String)value);
            }
        }
        ,
        CreationDate {
            public Object get(StnLineEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(StnLineEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(StnLineEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(StnLineEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(StnLineEOImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        Userid {
            public Object get(StnLineEOImpl obj) {
                return obj.getUserid();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setUserid((Number)value);
            }
        }
        ,
        Respid {
            public Object get(StnLineEOImpl obj) {
                return obj.getRespid();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setRespid((Number)value);
            }
        }
        ,
        Respapplid {
            public Object get(StnLineEOImpl obj) {
                return obj.getRespapplid();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setRespapplid((Number)value);
            }
        }
        ,
        Wash {
            public Object get(StnLineEOImpl obj) {
                return obj.getWash();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        HeaderEO {
            public Object get(StnLineEOImpl obj) {
                return obj.getHeaderEO();
            }

            public void put(StnLineEOImpl obj, Object value) {
                obj.setHeaderEO((HeaderEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(StnLineEOImpl object);

        public abstract void put(StnLineEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int STNLINEID = AttributesEnum.StnLineId.index();
    public static final int STN = AttributesEnum.Stn.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int BPO = AttributesEnum.Bpo.index();
    public static final int PART = AttributesEnum.Part.index();
    public static final int STNQTY = AttributesEnum.StnQty.index();
    public static final int PRODLINE = AttributesEnum.ProdLine.index();
    public static final int CHANGINVORG = AttributesEnum.ChangInvOrg.index();
    public static final int TIMECAL = AttributesEnum.TimeCal.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int USERID = AttributesEnum.Userid.index();
    public static final int RESPID = AttributesEnum.Respid.index();
    public static final int RESPAPPLID = AttributesEnum.Respapplid.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int HEADEREO = AttributesEnum.HeaderEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public StnLineEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.StnLineEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for StnLineId, using the alias name StnLineId.
     * @return the StnLineId
     */
    public Number getStnLineId() {
        return (Number)getAttributeInternal(STNLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for StnLineId.
     * @param value value to set the StnLineId
     */
    public void setStnLineId(Number value) {
        setAttributeInternal(STNLINEID, value);
    }

    /**
     * Gets the attribute value for Stn, using the alias name Stn.
     * @return the Stn
     */
    public String getStn() {
        return (String)getAttributeInternal(STN);
    }

    /**
     * Sets <code>value</code> as the attribute value for Stn.
     * @param value value to set the Stn
     */
    public void setStn(String value) {
        setAttributeInternal(STN, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the Color
     */
    public String getColor() {
        return (String)getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for Bpo, using the alias name Bpo.
     * @return the Bpo
     */
    public String getBpo() {
        return (String)getAttributeInternal(BPO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Bpo.
     * @param value value to set the Bpo
     */
    public void setBpo(String value) {
        setAttributeInternal(BPO, value);
    }

    /**
     * Gets the attribute value for Part, using the alias name Part.
     * @return the Part
     */
    public String getPart() {
        return (String)getAttributeInternal(PART);
    }

    /**
     * Sets <code>value</code> as the attribute value for Part.
     * @param value value to set the Part
     */
    public void setPart(String value) {
        setAttributeInternal(PART, value);
    }

    /**
     * Gets the attribute value for StnQty, using the alias name StnQty.
     * @return the StnQty
     */
    public Number getStnQty() {
        return (Number)getAttributeInternal(STNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for StnQty.
     * @param value value to set the StnQty
     */
    public void setStnQty(Number value) {
        setAttributeInternal(STNQTY, value);
    }

    /**
     * Gets the attribute value for ProdLine, using the alias name ProdLine.
     * @return the ProdLine
     */
    public Number getProdLine() {
        return (Number)getAttributeInternal(PRODLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProdLine.
     * @param value value to set the ProdLine
     */
    public void setProdLine(Number value) {
        setAttributeInternal(PRODLINE, value);
    }

    /**
     * Gets the attribute value for ChangInvOrg, using the alias name ChangInvOrg.
     * @return the ChangInvOrg
     */
    public String getChangInvOrg() {
        return (String)getAttributeInternal(CHANGINVORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChangInvOrg.
     * @param value value to set the ChangInvOrg
     */
    public void setChangInvOrg(String value) {
        setAttributeInternal(CHANGINVORG, value);
    }

    /**
     * Gets the attribute value for TimeCal, using the alias name TimeCal.
     * @return the TimeCal
     */
    public String getTimeCal() {
        return (String)getAttributeInternal(TIMECAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for TimeCal.
     * @param value value to set the TimeCal
     */
    public void setTimeCal(String value) {
        setAttributeInternal(TIMECAL, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date)getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for Userid, using the alias name Userid.
     * @return the Userid
     */
    public Number getUserid() {
        return (Number)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Userid.
     * @param value value to set the Userid
     */
    public void setUserid(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for Respid, using the alias name Respid.
     * @return the Respid
     */
    public Number getRespid() {
        return (Number)getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Respid.
     * @param value value to set the Respid
     */
    public void setRespid(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for Respapplid, using the alias name Respapplid.
     * @return the Respapplid
     */
    public Number getRespapplid() {
        return (Number)getAttributeInternal(RESPAPPLID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Respapplid.
     * @param value value to set the Respapplid
     */
    public void setRespapplid(Number value) {
        setAttributeInternal(RESPAPPLID, value);
    }

    /**
     * Gets the attribute value for Wash, using the alias name Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String)getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Wash.
     * @param value value to set the Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity HeaderEOImpl.
     */
    public HeaderEOImpl getHeaderEO() {
        return (HeaderEOImpl)getAttributeInternal(HEADEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity HeaderEOImpl.
     */
    public void setHeaderEO(HeaderEOImpl value) {
        setAttributeInternal(HEADEREO, value);
    }


    /**
     * @param stnLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number stnLineId) {
        return new Key(new Object[]{stnLineId});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        /* Sequence Generation Code of Header by PwC */  
        oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("MNJ_MFG_OSP_STN_LINE_S",getDBTransaction());          
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
        setStnLineId(sVal);
        /* End Sequence Generation Code of Header by PwC */
    }
    
    //  ---------------Method in EO For WHO Columns and Org -----------------------------------------------
          protected void doDML(int operation, TransactionEvent e) {
             
              Map sessionScope = ADFContext.getCurrent().getSessionScope();   
              String user = (String)sessionScope.get("userId");
              String org = (String)sessionScope.get("orgId");
              String RespId = (String)sessionScope.get("respId");
              if(DML_UPDATE == operation){
                  try {
                      setLastUpdatedDate((Date)Date.getCurrentDate()); 
                      setLastUpdatedBy(new oracle.jbo.domain.Number(user));
                  } catch (SQLException f) {
                      System.out.println(f.getMessage());
                  }
              }
              else if (DML_INSERT == operation){
               
                  try {
           
                      setCreationDate((Date)Date.getCurrentDate());  
                      setCreatedBy(new oracle.jbo.domain.Number(user));
                      setOrgId(new oracle.jbo.domain.Number(org));
                      setRespid(new oracle.jbo.domain.Number(RespId));
                  
                  } catch (SQLException f) {
                      ;
                  }
              }
              super.doDML(operation, e);
          }

    
    

}
