package mnj.mfg.model.lov.views;

import mnj.mfg.model.lov.views.common.DepartmentAssignPopUpRow;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 12 13:26:57 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentAssignPopUpRowImpl extends ViewRowImpl implements DepartmentAssignPopUpRow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Department {
            public Object get(DepartmentAssignPopUpRowImpl obj) {
                return obj.getDepartment();
            }

            public void put(DepartmentAssignPopUpRowImpl obj, Object value) {
                obj.setDepartment((String)value);
            }
        }
        ,
        SelectBox {
            public Object get(DepartmentAssignPopUpRowImpl obj) {
                return obj.getSelectBox();
            }

            public void put(DepartmentAssignPopUpRowImpl obj, Object value) {
                obj.setSelectBox((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(DepartmentAssignPopUpRowImpl object);

        public abstract void put(DepartmentAssignPopUpRowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int SELECTBOX = AttributesEnum.SelectBox.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentAssignPopUpRowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Department.
     * @return the Department
     */
    public String getDepartment() {
        return (String) getAttributeInternal(DEPARTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Department.
     * @param value value to set the  Department
     */
    public void setDepartment(String value) {
        setAttributeInternal(DEPARTMENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelectBox.
     * @return the SelectBox
     */
    public String getSelectBox() {
        return (String) getAttributeInternal(SELECTBOX);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelectBox.
     * @param value value to set the  SelectBox
     */
    public void setSelectBox(String value) {
        setAttributeInternal(SELECTBOX, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
