package mnj.mfg.model.lov.views.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 12 13:26:57 BDT 2018
// ---------------------------------------------------------------------
public interface DepartmentAssignPopUpRow extends Row {
    String getDepartment();

    void setDepartment(String value);

    String getSelectBox();

    void setSelectBox(String value);
}
